sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

script:
  # Build project
  - npm install
  - npm run build

  # Build docker image
  - docker build -t $DOCKER_USERNAME/scanservjs:$TRAVIS_BRANCH -f Dockerfile .

   # Push docker image
  - if [ ! -z "$TRAVIS_TAG" ] || [ "$TRAVIS_BRANCH" == "master" ] ; then
    docker tag $DOCKER_USERNAME/scanservjs:$TRAVIS_BRANCH $DOCKER_USERNAME/scanservjs:latest;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push $DOCKER_USERNAME/scanservjs:$TRAVIS_BRANCH;
    docker push $DOCKER_USERNAME/scanservjs:latest;
    fi
