name: Node.js CI

#on: [push]
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 6
      matrix:
        #node-version: [8.x, 10.x, 12.x]
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo sed -i 's/policy domain="coder" rights="none" pattern="PDF"/policy domain="coder" rights="read | write" pattern="PDF"'/ /etc/ImageMagick-6/policy.xml
    - run: npm install
    - run: npm run server-build
    - run: npm run client-build
    - run: npm run test
      env:
        CI: true
